name: mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - nltk
  - nltk_data
  - pandas
  - pip
  - pyspark
  - python=3.7
  - spacy
  - pip:
    - h2o==3.26.0.11
    - mlflow
    - spark-nlp

